services:

  # --- Nginx Reverse Proxy Service ---
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - portfolio
      - taskaru-frontend
      - taskaru-backend
      # - carpool
    networks:
      - app_network
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/:ro

  # --- Portfolio App Service ---
  portfolio:
    image: jyllandteodosio/portfolio-app:latest
    restart: always
    networks:
      - app_network

  # --- Taskaru App Frontend Service (Next.js/React) ---
  taskaru-frontend:
    image: jyllandteodosio/taskaru-frontend:latest
    # This service might need to communicate with the backend API internally.
    # expose:
    #   - "3000" 
    environment:
      NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    restart: always
    depends_on:
      - taskaru-backend
    networks:
      - app_network

  # --- Taskaru App Backend Service (Node.js API) ---
  taskaru-backend:
    image: jyllandteodosio/taskaru-backend:latest
    # This service needs to communicate with the MongoDB database internally.
    # expose:
    #   - "5000" # 
    environment:
      SESSION_SECRET: ${SESSION_SECRET}
      RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      MONGO_URI: ${MONGO_URI}
      DB_URI: ${DB_URI}
      CERT_FOLDER: ${CERT_FOLDER}
      CORS_ORIGIN: ${CORS_ORIGIN}
      CLIENT_URL: ${CLIENT_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    restart: always
    depends_on:
      - mongodb
    networks:
      - app_network

  # --- Taskaru App Database Service (MongoDB) ---
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    restart: always
    networks:
      - app_network
  # # --- Carpool App Service (Laravel) ---
  # carpool:
  #   image: jyllandteodosio/carpool-app:latest
  #   # This service needs to communicate with the MySQL database internally.
  #   # expose:
  #   #   - "80" # 
  #   environment:
  #     DB_CONNECTION: mysql
  #     DB_HOST: mysql
  #     DB_PORT: 3306
  #     DB_DATABASE: carpooldb
  #     DB_USERNAME: carpooluser
  #     DB_PASSWORD: carpoolpassword
  #     # Add other Laravel environment variables (.env)
  #   restart: always
  #   depends_on:
  #     - mysql
  #   networks:
  #     - app_network

  # # --- Carpool App Database Service (MySQL) ---
  # mysql:
  #   image: mysql:8.0
  #   environment:
  #     # Set MySQL root password (use secrets in production!)
  #     MYSQL_ROOT_PASSWORD: mysql_root_password
  #     # Create a database and user for the Carpool app
  #     MYSQL_DATABASE: carpooldb
  #     MYSQL_USER: carpooluser
  #     MYSQL_PASSWORD: carpoolpassword
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   restart: always
  #   networks:
  #     - app_network

  # Define the network for services to communicate
networks:
  app_network:
    driver: bridge

# Define named volumes for persistent data
volumes:
  mongodb_data:
  mysql_data:
